import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-zinc-50 text-zinc-900 dark:bg-black dark:text-zinc-50">
          <AppSidebar />
          <div className="flex flex-1 flex-col">
            <AppHeader />
            <div className="flex-1 px-6 pb-10 pt-6 md:px-10 lg:px-16">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

function AppHeader() {
  return (
    <header className="flex flex-col px-6 py-4 justify-between gap-4 border-b border-zinc-200 pb-4 dark:border-zinc-800 md:flex-row md:items-center">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">
          Automation Control Panel
        </h1>
        <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
          Manage accounts, monitor sessions, control automation, and keep your
          system safe.
        </p>
      </div>
    </header>
  );
}

